// components/GameCanvas.vue
<template>
  <canvas
    ref="canvasRef"
    class="block w-full h-full touch-none"
  />
</template>

<script lang="ts">
import {
  defineComponent,
  onBeforeUnmount,
  onMounted,
  PropType,
  ref,
} from '@nuxtjs/composition-api';
import { GameEngine } from '~/utils/gameEngine';

export default defineComponent({
  name: 'GameCanvas',
  props: {
    onScoreUpdate: {
      type: Function as PropType<(score: number) => void>,
      required: true,
    },
    onGameOver: {
      type: Function as PropType<(score: number) => void>,
      required: true,
    },
    boxStyle: {
      type: String as PropType<'legacy' | 'v2'>,
      default: 'legacy',
    },
  },
  setup(props) {
    const canvasRef = ref<HTMLCanvasElement | null>(null);
    const engineRef = ref<GameEngine | null>(null);

    const startGame = () => {
      engineRef.value?.start();
    };

    const handleTap = () => {
      engineRef.value?.handleInput();
    };

    onMounted(() => {
      if (!canvasRef.value) {
        return;
      }

      engineRef.value = new GameEngine(
        canvasRef.value,
        {
          onScoreUpdate: props.onScoreUpdate,
          onGameOver: props.onGameOver,
        },
        {
          boxStyle: props.boxStyle,
        }
      );
    });

    onBeforeUnmount(() => {
      engineRef.value?.cleanup();
    });

    return {
      canvasRef,
      handleTap,
      startGame,
    };
  },
});
</script>

// legacy-react/components/GameCanvas.tsx
import React, { useEffect, useRef, useImperativeHandle, forwardRef } from 'react';
import { GameEngine } from '../utils/gameEngine';

interface GameCanvasProps {
  onScoreUpdate: (score: number) => void;
  onGameOver: (score: number) => void;
  boxStyle?: 'legacy' | 'v2';
}

export interface GameCanvasHandle {
  startGame: () => void;
  handleTap: () => void;
}

const GameCanvas = forwardRef<GameCanvasHandle, GameCanvasProps>((props, ref) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const engineRef = useRef<GameEngine | null>(null);

  useImperativeHandle(ref, () => ({
    startGame: () => {
      engineRef.current?.start();
    },
    handleTap: () => {
      engineRef.current?.handleInput();
    }
  }));

  useEffect(() => {
    if (!canvasRef.current) return;

    const engine = new GameEngine(
      canvasRef.current,
      {
        onScoreUpdate: props.onScoreUpdate,
        onGameOver: props.onGameOver,
      },
      {
        boxStyle: props.boxStyle ?? 'legacy',
      }
    );
    engineRef.current = engine;

    return () => {
      engine.cleanup();
    };
  }, [props.onScoreUpdate, props.onGameOver]);

  return (
    <canvas
      ref={canvasRef}
      className="block w-full h-full touch-none"
    />
  );
});

GameCanvas.displayName = 'GameCanvas';
export default GameCanvas;
